
const ALL_COLUMNS = (
    "auxHeat1",
    "auxHeat2",
    "auxHeat3",
    "compCool1",
    "compCool2",
    "compHeat1",
    "compHeat2",
    "dehumidifier",
    "dmOffset",
    "economizer",
    "fan",
    "humidifier",
    "hvacMode",
    "outdoorHumidity",
    "outdoorTemp",
    "sky",
    "ventilator",
    "wind",
    "zoneAveTemp",
    "zoneCalendarEvent",
    "zoneClimate",
    "zoneCoolTemp",
    "zoneHeatTemp",
    "zoneHumidity",
    "zoneHumidityHigh",
    "zoneHumidityLow",
    "zoneHvacMode",
    "zoneOccupancy"
  )
  
  const DEFAULT_COLUMNS = (
      "compCool1",
      "compHeat1",
      "fan",
      "hvacMode",
      "outdoorHumidity",
      "outdoorTemp",
      "zoneAveTemp",
      "zoneClimate",
      "zoneCoolTemp",
      "zoneHeatTemp",
      "zoneHumidity",
      "zoneHvacMode",
      "zoneOccupancy"
  )

const COLUMN_TITLE_LOOKUP = Dict(
    "auxHeat1" => "Aux Heat (sec)",
    "auxHeat2" => "Aux Heat Stage 2 (sec)",
    "auxHeat3" => "Aux Heat Stage 3 (sec)",
    "compCool1" => "Cool Stage 1 (sec)",
    "compCool2" => "Cool Stage 2 (sec)",
    "compHeat1" => "Heat Stage 1 (sec)",
    "compHeat2" => "Heat Stage 2 (sec)",
    "dehumidifier" => "Dehumidifier (sec)",
    "dmOffset" => "Demand Mgmt Offset (F)",
    "economizer" => "Economizer Runtime (sec)",
    "fan" => "Fan (sec)",
    "humidifier" => "Humidifier (sec)",
    "hvacMode" => "HVAC Mode",
    "outdoorHumidity" => "Outdoor Humidity (%)",
    "outdoorTemp" => "Outdoor Temp (F)",
    "sky" => "Sky Cover",
    "ventilator" => "Ventilator (sec)",
    "wind" => "Wind Speed (km/h)",
    "zoneAveTemp" => "Indoor Temp Avg (F)",
    "zoneCalendarEvent" => "Override Event",
    "zoneClimate" => "Climate Mode",
    "zoneCoolTemp" => "Zone Cool Temp",
    "zoneHeatTemp" => "Zone Heat Temp",
    "zoneHumidity" => "Humidity Avg (%)",
    "zoneHumidityHigh" => "Humidity High (%)",
    "zoneHumidityLow" => "Humidity Low (%)",
    "zoneHvacMode" => "HVAC System Mode",
    "zoneOccupancy" => "Zone Occupancy"
)
